- hosts: localhost
  gather_facts: false
  connection: local
  vars:
   ontap_vserver: svm_test
  tasks:
  - name: create netapp volume
    netapp.ontap.na_ontap_volume:
      state: present
      name: "{{ volume_name }}"
      aggregate_name: aggr1
      junction_path: "/{{ volume_name }}"
      size: "{{ volume_size }}"
      policy: "export-{{ ontap_vserver }}"
      vserver: "{{ ontap_vserver }}"
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
    delegate_to: localhost
