- hosts: localhost
  gather_facts: false
  connection: local
  vars:
   ontap_vserver: svm_ansible
  tasks:
  - name: Create FlexVol
    netapp.ontap.na_ontap_volume:
      state: present
      name: "{{ volume_name }}"
      aggregate_name: aggr1
      size: "{{ volume_size }}"
      vserver: "{{ ontap_vserver }}"
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
   delegate_to: localhost
